export const curriculumUrl = "https://antk.uni-nke.hu/document/akk-copy-uni-nke-hu/International%20Cybersecurity%20Studies%20MA%20-%20tanterv.pdf#page=48";
export const topics = [
  "General security concepts", "Threat actors and attack vectors", "Vulnerabilities and exploits",
  "Mitigation techniques", "Security architectures", "Data security and resilience",
  "Secure operations lifecycle", "Vulnerability and incident management", "Network, endpoint and identity protection",
  "Orchestration, automation and response", "Governance and risk management", "Compliance and supply-chain security",
  "Audits and awareness", "Current threats and defences",
];
export type Card = { id: string; topic: number; question: string; answer: string; example: string };
const content: string[][][] = [
[
["How is information different from data?", "Data consists of recorded facts or observations. Information is data interpreted in context so it has meaning.", "A value of 39 becomes useful information when you know it is a patient's temperature in degrees Celsius."],
["What does the CIA triad stand for?", "Confidentiality, integrity and availability: protecting information from unauthorised disclosure, improper alteration, and loss of timely access.", "Payroll needs private salaries, accurate amounts and access on payday."],
["What is an asset in cybersecurity?", "Anything valuable to an organisation that needs protection, including information, systems, services, people and business processes.", "A university's enrolment service is an asset, as are the records and staff supporting it."],
["How do a threat, vulnerability and risk differ?", "A threat can cause harm; a vulnerability is a weakness it may exploit; risk concerns the likelihood and impact of a harmful event in context.", "An attacker exploiting an unpatched portal could disclose student records."],
["A service stops working, but no records are stolen or changed. Which CIA objective is affected?", "Availability: authorised users cannot access the service when they need it.", "A broken network cable can create an availability problem without an attacker."],
["Who is responsible for cybersecurity in an organisation?", "Responsibility is shared. Leadership sets direction and accepts risk, owners protect their processes, and staff follow and improve agreed controls.", "IT configures access; a department manager decides who needs access to that department's data."],
["How do authentication and authorisation differ?", "Authentication checks a claimed identity. Authorisation determines what that identity is allowed to do.", "Signing in identifies you; permission to edit grades is a separate decision."],
["What is the difference between a security policy and a procedure?", "A policy states requirements and intent. A procedure gives the steps for carrying out a task consistently.", "A policy requires access removal; a leaver procedure lists who removes which accounts and when."],
],
[
["Name three common motivations for a cyberattack.", "Financial gain, espionage and disruption are common motivations. Ideology, revenge or status can also matter.", "A criminal may demand a ransom, while a state-linked actor may seek intelligence."],
["What is an attack vector?", "The route or method used to gain access to a target or deliver an attack.", "A phishing email, an exposed remote-access service or a compromised software update."],
["How does spear phishing differ from general phishing?", "Spear phishing targets a particular person or group using tailored context. General phishing is usually sent broadly.", "A fake message mentioning your actual course and lecturer is tailored to you."],
["What is social engineering?", "Manipulating people into revealing information or taking actions that undermine security.", "A caller pretends to be IT support and asks you to approve an unexpected sign-in."],
["Can an insider threat be unintentional?", "Yes. People with legitimate access can cause harm through mistakes, negligence or compromised accounts, as well as malicious actions.", "Sending a sensitive attachment to the wrong recipient can cause a breach."],
["Why is an attacker's motivation useful when selecting controls?", "It helps identify likely targets and consequences, so the organisation can prioritise relevant defences and monitoring.", "A research lab may prioritise protecting intellectual property against espionage."],
["What is an attack surface?", "The collection of exposed points where someone could interact with or attack a system.", "Public web services, remote access, user accounts and third-party connections all contribute."],
["How can OSINT support an attacker?", "Public information can reveal relationships, systems or routines that help an attacker plan and tailor an approach.", "A public staff directory can help make an impersonation message convincing."],
],
[
["How is an exploit different from a vulnerability?", "A vulnerability is a weakness. An exploit is a technique or code that takes advantage of a weakness.", "Missing input validation is a weakness; an input that abuses it is part of an exploit."],
["Does every vulnerability immediately mean an organisation has been compromised?", "No. Exposure, exploitability and evidence of actual exploitation must be considered separately.", "A vulnerable component may be isolated, although it still needs assessment."],
["What is a zero-day vulnerability?", "A vulnerability for which defenders have had no advance opportunity to prepare an effective fix when it becomes known or is exploited; usage of the term varies.", "An attacker abuses a newly discovered flaw before a vendor patch is available."],
["What does a CVE identifier identify?", "A publicly disclosed cybersecurity vulnerability. The identifier provides a common reference; it does not by itself describe business risk.", "Different security tools can use the same CVE identifier to refer to one vulnerability."],
["Why is a CVSS score insufficient to prioritise all patching?", "It describes technical severity. Prioritisation also needs exposure, active exploitation, asset importance and compensating controls.", "An internet-facing critical service may need attention before a higher-scoring isolated test system."],
["Can a configuration error create a vulnerability without a software bug?", "Yes. Excessive permissions, default credentials and unnecessarily exposed services can create exploitable weaknesses.", "A storage location made publicly readable can expose files even if its software is fully patched."],
["What is an injection vulnerability?", "Untrusted input is interpreted as commands or code instead of being handled only as data.", "Parameterised database queries help separate input data from SQL instructions."],
["What does a vulnerability scanner's finding still need?", "Validation and context: confirm the affected asset, accuracy, exposure and likely business impact before deciding treatment.", "A scanner may report a version-based issue that a vendor has already fixed through a backported patch."],
],
[
["What is defence in depth?", "Using multiple complementary layers of protection so a single failed control does not expose everything.", "Email filtering, staff awareness, MFA and endpoint monitoring address different parts of an attack."],
["What is least privilege?", "Grant only the access needed for a task, for only as long as needed, and review it when circumstances change.", "A temporary contractor gets access to the project folder rather than the whole department drive."],
["How do preventive, detective and corrective controls differ?", "Preventive controls reduce the chance of an event, detective controls identify events, and corrective controls restore or improve the situation.", "An access rule prevents, a suspicious-login alert detects, and account recovery corrects."],
["Why is patching a risk-management activity?", "Patches can reduce exploitable weaknesses, but teams must prioritise, test and deploy them while managing service disruption.", "A critical patch may need an emergency change with a rollback plan."],
["What is a compensating control?", "An alternative measure that addresses a control objective or reduces the same risk when the preferred control cannot be implemented.", "Isolating an unpatchable device and restricting access may reduce exposure until replacement."],
["Why should unused services and ports be disabled?", "They add possible entry points and maintenance responsibilities without providing a necessary business benefit.", "Disable an unused remote-management service on a server."],
["What is the purpose of security hardening?", "Reducing unnecessary functionality and applying secure configurations to make a system harder to misuse or compromise.", "Remove default accounts, limit permissions and enable useful security logs."],
["Why should a control be tested after implementation?", "A configured control may be ineffective, incorrectly scoped or disruptive. Testing checks that it meets its objective in practice.", "After changing firewall rules, verify both that unwanted access is blocked and the application still works."],
],
[
["What is network segmentation?", "Dividing a network into separate zones and controlling communication between them.", "A guest Wi-Fi network should not have unrestricted access to student-record systems."],
["What does zero trust mean at a high level?", "Access should be explicitly evaluated and limited rather than trusted merely because a user or device is inside a network.", "A request to a sensitive application is checked even when it comes from an office computer."],
["Why place a public web server in a separate network zone?", "To limit how a compromise of an exposed service could reach more sensitive internal systems.", "The web server can reach only the database service it needs, not every internal workstation."],
["What is a trust boundary?", "A point where data or requests cross between areas with different trust assumptions or security controls.", "User input crossing from a browser into a server must be validated."],
["What is a single point of failure?", "A component whose failure can stop the whole service because no effective alternative exists.", "Two servers still share a single point of failure if both depend on one unprotected power supply."],
["Why is cloud security a shared responsibility?", "Provider and customer duties depend on the service model. Customers still have responsibilities such as identity, data handling and configuration.", "A cloud provider securing its hardware does not make a customer's public storage settings safe."],
["What is the purpose of a threat model?", "To understand the system, its assets, likely threats and weaknesses, then choose and review appropriate mitigations.", "Map how a student uploads a file and identify where untrusted data crosses boundaries."],
["How do fail-open and fail-closed behaviour differ?", "Fail-open permits access when a control fails; fail-closed denies it. The choice must consider both security and operational or safety needs.", "An access gateway failure should have a deliberately chosen behaviour, not an accidental default."],
],
[
["What are data at rest and data in transit?", "Data at rest is stored; data in transit is moving between systems or components.", "A saved backup is at rest; a file transfer over a network is in transit."],
["How does encryption differ from hashing?", "Encryption transforms data so authorised parties with the right key can recover it. A cryptographic hash produces a digest and is not designed to be reversed.", "Encrypt a confidential file; compare trusted hashes to check whether downloaded content has changed."],
["Why does encryption require key management?", "Protection depends on how keys are generated, stored, accessed, rotated and recovered. Exposed or lost keys can defeat the intended protection.", "Keeping the decryption key next to publicly readable encrypted data can undermine confidentiality."],
["How does a backup differ from high availability?", "A backup supports recovery of earlier data. High availability keeps a service running through failures. They address different problems.", "Replication may quickly copy an accidental deletion; a recoverable backup may still be needed."],
["What does RPO describe?", "Recovery point objective describes the maximum tolerable period of data loss, measured back from a disruption.", "An RPO of one hour means planning to lose no more than about an hour of data."],
["What does RTO describe?", "Recovery time objective is the target time within which a service should be restored after disruption.", "An RTO of four hours guides recovery resources and procedures."],
["Why must backup restoration be tested?", "A completed backup job does not prove that data is usable or that the service can be restored within its objectives.", "Run a controlled restore and check the application can use the recovered records."],
["How does data classification help security?", "It groups information by sensitivity or importance so handling, access and protection requirements can be applied consistently.", "Public course descriptions and confidential assessment records need different access rules."],
],
[
["What does secure by design mean?", "Considering security requirements and failure cases from the beginning and throughout a system's lifecycle.", "Plan account recovery and access boundaries before releasing a service."],
["Why is a change-management process useful?", "It helps teams assess, approve, test and record changes while planning how to recover if something goes wrong.", "A network change includes an impact assessment and a tested rollback option."],
["What is separation of duties?", "Dividing critical responsibilities so one person cannot perform all parts of a sensitive process without oversight.", "The person requesting a payment does not also approve it."],
["Why should development and production be separated?", "Different access, data and change controls reduce the chance that experiments or compromised development resources affect live services.", "Use synthetic records in testing instead of copying unrestricted student data."],
["What should happen when a system reaches end of support?", "Assess the risk and plan replacement, retirement or documented interim controls. Unsupported software may no longer receive needed fixes.", "An obsolete server is isolated while a funded migration is completed."],
["Why is logging part of secure operations?", "Relevant logs help detect problems, investigate events and demonstrate that controls operated. Logs themselves need access and integrity protection.", "Record who changed a privileged account and when."],
["What is configuration drift?", "A system's settings gradually diverge from its approved baseline, potentially creating weaknesses or operational inconsistency.", "A temporary debugging setting stays enabled after maintenance."],
["What does secure decommissioning include?", "Remove access and integrations, preserve required records, and sanitise or destroy data-bearing media appropriately before disposal.", "Retiring an application includes its service accounts, tokens and stored backups."],
],
[
["What are the main activities in vulnerability management?", "Maintain asset knowledge, find and assess weaknesses, prioritise treatment, remediate or mitigate, and verify closure continuously.", "A patched finding remains open until the relevant system has been checked."],
["How does a security event differ from an incident?", "An event is an observable occurrence. An incident is an occurrence assessed as jeopardising security or violating relevant policy and needing a response.", "One failed login is an event; confirmed account takeover is an incident."],
["What is the purpose of incident containment?", "Limit an incident's spread and damage while considering business impact and preserving useful evidence.", "Isolate a compromised endpoint according to the response plan."],
["How does eradication differ from recovery?", "Eradication removes the cause and unwanted access. Recovery restores services safely and checks they remain trustworthy.", "Remove persistence and fix the entry point before returning a system to normal use."],
["Why preserve evidence during incident handling?", "Reliable records help reconstruct events, support decisions and enable any later investigation. Handling should be documented.", "Record collection times and who handled a forensic copy."],
["What should an employee do after noticing a suspected phishing compromise?", "Promptly use the organisation's reporting process and follow response instructions. Preserve relevant information rather than hiding the mistake.", "Report the message, approximate time and actions already taken."],
["Why perform lessons learned after an incident?", "Identify what worked, what failed and which improvements have owners and deadlines.", "An incident may reveal that an escalation contact list was outdated."],
["What is the value of a known-exploited-vulnerability catalogue?", "It provides evidence of real-world exploitation that can inform prioritisation alongside exposure and business impact.", "An actively exploited flaw on an exposed service may deserve urgent treatment."],
],
[
["What does a firewall primarily do?", "Allow or block network traffic according to rules. Its effectiveness depends on placement, configuration and the traffic it can inspect.", "Permit the application connection needed by users while blocking unnecessary inbound access."],
["How do IDS and IPS differ?", "An intrusion detection system identifies and alerts on suspicious activity; an intrusion prevention system can also block activity in its traffic path.", "Blocking introduces a need to manage the impact of false positives."],
["What is EDR used for?", "Endpoint detection and response helps collect endpoint activity, investigate suspicious behaviour and take response actions.", "An analyst uses endpoint telemetry to investigate unusual process execution."],
["What makes authentication multi-factor?", "It combines different factor types, such as something you know, have or are. Two passwords are still one factor type.", "A password plus a hardware security key combines knowledge and possession."],
["What is role-based access control?", "Permissions are assigned to roles, and users receive permissions through their approved role membership.", "A course administrator role may manage enrolment without editing examination grades."],
["Why are joiner, mover and leaver processes necessary?", "They align access with a person's current responsibilities and remove access that is no longer justified.", "Moving departments should remove old permissions as well as adding new ones."],
["What is privileged access management intended to reduce?", "The risk from powerful accounts through measures such as controlled elevation, time limits, credential protection and activity oversight.", "An administrator receives temporary elevated access for an approved maintenance task."],
["Does a VPN make everything a user does safe?", "No. It protects a connection within its scope, but does not fix a compromised device, phishing or excessive access permissions.", "Malware on a laptop can remain dangerous while that laptop is connected through a VPN."],
],
[
["What does a SIEM help a security team do?", "Collect and analyse security-related logs, correlate events, and support detection and investigation.", "Combine sign-in and endpoint events to investigate a suspicious account."],
["What does SOAR stand for?", "Security orchestration, automation and response: coordinating tools and response workflows, often using playbooks.", "A playbook enriches a suspicious domain and creates an investigation ticket."],
["How does orchestration differ from automation?", "Automation executes a task with reduced manual effort. Orchestration coordinates several tasks or systems into a workflow.", "Looking up an indicator is automation; coordinating lookup, triage and approval is orchestration."],
["What is a security playbook?", "A documented or executable workflow describing how to handle a particular situation, including decisions and escalation.", "A phishing playbook specifies validation, containment and communication steps."],
["Why might an automated response require human approval?", "Some actions can disrupt services or affect many users, so confidence and business impact need review.", "Disabling a shared service account might interrupt a critical application."],
["What is a false positive in security detection?", "An alert that identifies benign activity as suspicious or malicious for the detection objective.", "An authorised administrator's unusual maintenance action triggers an attack alert."],
["What is alert fatigue?", "Too many low-value or repetitive alerts reduce attention and can delay responses to significant events.", "Tune a noisy rule and preserve alerts that identify meaningful risk."],
["Why should a response automation be tested before broad use?", "Incorrect assumptions, permissions or integrations can amplify mistakes. Controlled testing checks actions, failure handling and rollback.", "Test an account-blocking playbook on a designated test account."],
],
[
["What is security governance?", "The direction, accountability and oversight that align security with organisational objectives and risk decisions.", "Leadership defines who can accept a significant security risk."],
["What is an ISMS?", "An information security management system: a coordinated set of policies, processes, responsibilities and continual improvement for managing information-security risk.", "Its scope, risk assessment and evidence should reflect the organisation it serves."],
["How do inherent and residual risk differ?", "Inherent risk is assessed before considering relevant controls; residual risk remains after considering those controls.", "MFA can reduce account-takeover risk, but does not eliminate all ways an account can be compromised."],
["What are four common risk treatment options?", "Avoid, reduce or modify, share or transfer, and accept. Terminology varies; decisions should have an accountable owner.", "Insurance may transfer some financial consequences without removing the underlying technical risk."],
["What should a clear risk statement connect?", "A relevant asset or process, a threat event or cause, and a meaningful consequence, supported by context.", "If ransomware interrupts enrolment because recovery is ineffective, students may miss registration deadlines."],
["How does risk appetite differ from an individual risk acceptance?", "Risk appetite sets the broad amount and type of risk an organisation is willing to pursue or retain. Acceptance is a decision about a specific risk.", "Accepting an exception should identify the owner, rationale and review date."],
["How do a control's design and operating effectiveness differ?", "Design asks whether the control could achieve its objective. Operating effectiveness asks whether it actually worked consistently over the relevant period.", "A good access-review procedure is insufficient if reviews were not performed."],
["Why is business impact important when prioritising security work?", "Technical issues matter through their consequences for people, services, information and organisational objectives.", "A small configuration flaw on a life-critical service may deserve more attention than a noisy test-system alert."],
],
[
["How does compliance differ from security?", "Compliance addresses applicable requirements; security manages protection and risk in practice. Meeting a checklist does not demonstrate that every important risk is controlled.", "An organisation may pass a scoped assessment while still having unexamined weaknesses elsewhere."],
["At a high level, what is NIS2 intended to improve?", "Cybersecurity risk management, reporting and supervision for covered entities in the EU. Exact obligations depend on scope and applicable national implementation.", "Check the organisation's sector and applicable rules before deciding which duties apply."],
["What does ISO/IEC 27001 concern?", "Requirements for establishing, implementing, maintaining and continually improving an information security management system.", "A certificate applies to its stated scope; it is not a guarantee that no incident can occur."],
["Why assess a supplier before granting access to your systems or data?", "A supplier's practices, access and dependencies can introduce risk to your own processes and information.", "A payroll provider's access to staff records needs clear safeguards and responsibilities."],
["What should supplier security requirements address?", "Relevant access and data handling, security responsibilities, incident communication, assurance, continuity and exit arrangements.", "Agree how quickly a supplier must notify you of an incident affecting your service."],
["What is a software supply-chain attack?", "An attack that reaches a target by compromising software components, build processes, distribution or other trusted dependencies.", "A compromised update mechanism can distribute malicious changes to customers."],
["What is an SBOM?", "A software bill of materials: an inventory of software components and their relationships. It supports dependency visibility but does not prove software is secure.", "An SBOM can help locate products containing a newly vulnerable library."],
["Why is supplier offboarding part of security?", "Relationships end, but access, retained data and dependencies can remain unless they are deliberately addressed.", "Revoke supplier accounts and agree how data is returned or securely deleted."],
],
[
["What is the purpose of a security audit?", "Evaluate evidence against defined criteria and scope to determine whether requirements or controls are being met.", "An audit may sample access removals against the organisation's leaver procedure."],
["What makes audit evidence useful?", "It must be relevant, sufficiently reliable and sufficient for the conclusion, with context such as scope and time period.", "A screenshot of today's setting does not prove it remained correct throughout last year."],
["How does an audit differ from a penetration test?", "An audit evaluates against criteria; a penetration test attempts authorised exploitation within agreed scope. Their findings can complement each other.", "An audit checks patch governance, while a penetration test may demonstrate the impact of an exploitable system."],
["What should an actionable audit finding include?", "The expected requirement, observed condition and supporting evidence, the resulting risk, and a clear corrective action with an owner and due date.", "A finding identifies which sampled leaver accounts stayed active and why that matters."],
["Why is audit sampling used, and what is its limitation?", "Sampling makes review feasible, but conclusions are limited by sample design, coverage and evidence quality.", "Finding no errors in five records does not prove every record is correct."],
["What is the goal of security awareness training?", "Help people recognise relevant risks and take practical protective actions, including timely reporting.", "Staff practise verifying an unusual payment request through an independent channel."],
["Why is course completion alone a weak measure of awareness effectiveness?", "Attendance or completion shows participation, not necessarily understanding or changed behaviour.", "Use scenario responses and reporting behaviour alongside completion records."],
["Why encourage a supportive reporting culture?", "People are more likely to report mistakes and suspicious activity early when the process is clear and constructive.", "A quickly reported mistaken approval may allow rapid containment."],
],
[
["How can generative AI affect social engineering?", "It can help produce convincing, tailored text, images or voice at scale. Familiar verification and access controls still matter.", "Verify an urgent request through a known channel rather than trusting a familiar-sounding voice."],
["Does an authentic-looking video prove a claim is true?", "No. Check the source, context, supporting evidence and whether the content has been manipulated or misrepresented.", "A real old video can also mislead when presented as a current event."],
["Why can ransomware affect more than availability?", "Attackers may steal data, alter information or threaten disclosure as well as encrypting systems.", "Restoring backups does not undo disclosure of stolen records."],
["What is a vulnerability disclosure programme meant to provide?", "A defined way to report and handle security weaknesses, including scope and communication expectations.", "Finding a flaw does not automatically authorise testing systems outside an agreed scope."],
["What does cryptographic agility mean?", "The ability to change algorithms, protocols and keys without redesigning an entire system when security needs change.", "Maintain an inventory of where cryptography is used so migration can be planned."],
["What is prompt injection in an AI-enabled application?", "Untrusted content tries to cause a model or connected workflow to follow instructions that conflict with its intended task or controls.", "A retrieved document tells an assistant to expose information instead of summarising the document."],
["Why do new threats rarely make basic security controls irrelevant?", "New techniques often still depend on familiar weaknesses such as poor access control, exposed systems or ineffective recovery.", "Strong identity controls and tested incident response remain useful when an attack uses AI-generated content."],
["How should an organisation evaluate a newly advertised security tool?", "Start with the problem, evidence, environment and operational fit. Test whether it improves relevant outcomes before relying on claims.", "A small pilot can reveal whether a tool reduces meaningful risk or only produces more alerts."],
],
];
export const cards: Card[] = content.flatMap((group, topic) => group.map(([question, answer, example], index) => ({
  id: `t${String(topic + 1).padStart(2, "0")}-${String(index + 1).padStart(2, "0")}`,
  topic, question, answer, example,
})));
export const cardMap = new Map(cards.map(card => [card.id, card]));
